### PR TITLE
Small content fixes and a better example of stress

### PR DESCRIPTION
**Pull request by mezohe**

### CODE REVIEW

**Comment by russelleh** [comment]
Thanks!

**Comment by russelleh** [comment]
I intentionally didn't use "lo pa smani" because "la pa smani" has the same effect.

**Comment by russelleh** [comment]
Fixed in #57

**Comment by mezohe** [comment]
> I intentionally didn't use "lo pa smani" because "la pa smani" has the same effect.

What do you mean by this? In {la PA broda} the {PA} is part of the name -- {la ci blacykabri} can refer to a single restaurant -- while {lo PA broda} always refers to broda that are PA in number. I suggested adding the {lo} to stop people from assuming that a bare brivla can act as a sumti. (We often get newcomers saying things like *{prenu cu bajra} or *{mi djuno fi cmaci})

**Pull request closed without merging**
